# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/unixaccount/workspace/DCNN

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/unixaccount/workspace/DCNN

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/unixaccount/workspace/DCNN/CMakeFiles /home/unixaccount/workspace/DCNN//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/unixaccount/workspace/DCNN/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mnist_cnn_trainer

# Build rule for target.
mnist_cnn_trainer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mnist_cnn_trainer
.PHONY : mnist_cnn_trainer

# fast build rule for target.
mnist_cnn_trainer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mnist_cnn_trainer.dir/build.make CMakeFiles/mnist_cnn_trainer.dir/build
.PHONY : mnist_cnn_trainer/fast

#=============================================================================
# Target rules for targets named cifar10_cnn_trainer

# Build rule for target.
cifar10_cnn_trainer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cifar10_cnn_trainer
.PHONY : cifar10_cnn_trainer

# fast build rule for target.
cifar10_cnn_trainer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cifar10_cnn_trainer.dir/build.make CMakeFiles/cifar10_cnn_trainer.dir/build
.PHONY : cifar10_cnn_trainer/fast

#=============================================================================
# Target rules for targets named cifar100_cnn_trainer

# Build rule for target.
cifar100_cnn_trainer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cifar100_cnn_trainer
.PHONY : cifar100_cnn_trainer

# fast build rule for target.
cifar100_cnn_trainer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cifar100_cnn_trainer.dir/build.make CMakeFiles/cifar100_cnn_trainer.dir/build
.PHONY : cifar100_cnn_trainer/fast

#=============================================================================
# Target rules for targets named uji_ips_trainer

# Build rule for target.
uji_ips_trainer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uji_ips_trainer
.PHONY : uji_ips_trainer

# fast build rule for target.
uji_ips_trainer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uji_ips_trainer.dir/build.make CMakeFiles/uji_ips_trainer.dir/build
.PHONY : uji_ips_trainer/fast

#=============================================================================
# Target rules for targets named mnist_cnn_test

# Build rule for target.
mnist_cnn_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mnist_cnn_test
.PHONY : mnist_cnn_test

# fast build rule for target.
mnist_cnn_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mnist_cnn_test.dir/build.make CMakeFiles/mnist_cnn_test.dir/build
.PHONY : mnist_cnn_test/fast

#=============================================================================
# Target rules for targets named pipeline_test

# Build rule for target.
pipeline_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pipeline_test
.PHONY : pipeline_test

# fast build rule for target.
pipeline_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipeline_test.dir/build.make CMakeFiles/pipeline_test.dir/build
.PHONY : pipeline_test/fast

#=============================================================================
# Target rules for targets named network_worker

# Build rule for target.
network_worker: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 network_worker
.PHONY : network_worker

# fast build rule for target.
network_worker/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/network_worker.dir/build.make CMakeFiles/network_worker.dir/build
.PHONY : network_worker/fast

#=============================================================================
# Target rules for targets named distributed_pipeline_docker

# Build rule for target.
distributed_pipeline_docker: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 distributed_pipeline_docker
.PHONY : distributed_pipeline_docker

# fast build rule for target.
distributed_pipeline_docker/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distributed_pipeline_docker.dir/build.make CMakeFiles/distributed_pipeline_docker.dir/build
.PHONY : distributed_pipeline_docker/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named run_tests

# Build rule for target.
run_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_tests
.PHONY : run_tests

# fast build rule for target.
run_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/build
.PHONY : run_tests/fast

cifar100_cnn_trainer.o: cifar100_cnn_trainer.cpp.o
.PHONY : cifar100_cnn_trainer.o

# target to build an object file
cifar100_cnn_trainer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cifar100_cnn_trainer.dir/build.make CMakeFiles/cifar100_cnn_trainer.dir/cifar100_cnn_trainer.cpp.o
.PHONY : cifar100_cnn_trainer.cpp.o

cifar100_cnn_trainer.i: cifar100_cnn_trainer.cpp.i
.PHONY : cifar100_cnn_trainer.i

# target to preprocess a source file
cifar100_cnn_trainer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cifar100_cnn_trainer.dir/build.make CMakeFiles/cifar100_cnn_trainer.dir/cifar100_cnn_trainer.cpp.i
.PHONY : cifar100_cnn_trainer.cpp.i

cifar100_cnn_trainer.s: cifar100_cnn_trainer.cpp.s
.PHONY : cifar100_cnn_trainer.s

# target to generate assembly for a file
cifar100_cnn_trainer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cifar100_cnn_trainer.dir/build.make CMakeFiles/cifar100_cnn_trainer.dir/cifar100_cnn_trainer.cpp.s
.PHONY : cifar100_cnn_trainer.cpp.s

cifar10_cnn_trainer.o: cifar10_cnn_trainer.cpp.o
.PHONY : cifar10_cnn_trainer.o

# target to build an object file
cifar10_cnn_trainer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cifar10_cnn_trainer.dir/build.make CMakeFiles/cifar10_cnn_trainer.dir/cifar10_cnn_trainer.cpp.o
.PHONY : cifar10_cnn_trainer.cpp.o

cifar10_cnn_trainer.i: cifar10_cnn_trainer.cpp.i
.PHONY : cifar10_cnn_trainer.i

# target to preprocess a source file
cifar10_cnn_trainer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cifar10_cnn_trainer.dir/build.make CMakeFiles/cifar10_cnn_trainer.dir/cifar10_cnn_trainer.cpp.i
.PHONY : cifar10_cnn_trainer.cpp.i

cifar10_cnn_trainer.s: cifar10_cnn_trainer.cpp.s
.PHONY : cifar10_cnn_trainer.s

# target to generate assembly for a file
cifar10_cnn_trainer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cifar10_cnn_trainer.dir/build.make CMakeFiles/cifar10_cnn_trainer.dir/cifar10_cnn_trainer.cpp.s
.PHONY : cifar10_cnn_trainer.cpp.s

distributed_pipeline_docker.o: distributed_pipeline_docker.cpp.o
.PHONY : distributed_pipeline_docker.o

# target to build an object file
distributed_pipeline_docker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distributed_pipeline_docker.dir/build.make CMakeFiles/distributed_pipeline_docker.dir/distributed_pipeline_docker.cpp.o
.PHONY : distributed_pipeline_docker.cpp.o

distributed_pipeline_docker.i: distributed_pipeline_docker.cpp.i
.PHONY : distributed_pipeline_docker.i

# target to preprocess a source file
distributed_pipeline_docker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distributed_pipeline_docker.dir/build.make CMakeFiles/distributed_pipeline_docker.dir/distributed_pipeline_docker.cpp.i
.PHONY : distributed_pipeline_docker.cpp.i

distributed_pipeline_docker.s: distributed_pipeline_docker.cpp.s
.PHONY : distributed_pipeline_docker.s

# target to generate assembly for a file
distributed_pipeline_docker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distributed_pipeline_docker.dir/build.make CMakeFiles/distributed_pipeline_docker.dir/distributed_pipeline_docker.cpp.s
.PHONY : distributed_pipeline_docker.cpp.s

mnist_cnn_test.o: mnist_cnn_test.cpp.o
.PHONY : mnist_cnn_test.o

# target to build an object file
mnist_cnn_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mnist_cnn_test.dir/build.make CMakeFiles/mnist_cnn_test.dir/mnist_cnn_test.cpp.o
.PHONY : mnist_cnn_test.cpp.o

mnist_cnn_test.i: mnist_cnn_test.cpp.i
.PHONY : mnist_cnn_test.i

# target to preprocess a source file
mnist_cnn_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mnist_cnn_test.dir/build.make CMakeFiles/mnist_cnn_test.dir/mnist_cnn_test.cpp.i
.PHONY : mnist_cnn_test.cpp.i

mnist_cnn_test.s: mnist_cnn_test.cpp.s
.PHONY : mnist_cnn_test.s

# target to generate assembly for a file
mnist_cnn_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mnist_cnn_test.dir/build.make CMakeFiles/mnist_cnn_test.dir/mnist_cnn_test.cpp.s
.PHONY : mnist_cnn_test.cpp.s

mnist_cnn_trainer.o: mnist_cnn_trainer.cpp.o
.PHONY : mnist_cnn_trainer.o

# target to build an object file
mnist_cnn_trainer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mnist_cnn_trainer.dir/build.make CMakeFiles/mnist_cnn_trainer.dir/mnist_cnn_trainer.cpp.o
.PHONY : mnist_cnn_trainer.cpp.o

mnist_cnn_trainer.i: mnist_cnn_trainer.cpp.i
.PHONY : mnist_cnn_trainer.i

# target to preprocess a source file
mnist_cnn_trainer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mnist_cnn_trainer.dir/build.make CMakeFiles/mnist_cnn_trainer.dir/mnist_cnn_trainer.cpp.i
.PHONY : mnist_cnn_trainer.cpp.i

mnist_cnn_trainer.s: mnist_cnn_trainer.cpp.s
.PHONY : mnist_cnn_trainer.s

# target to generate assembly for a file
mnist_cnn_trainer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mnist_cnn_trainer.dir/build.make CMakeFiles/mnist_cnn_trainer.dir/mnist_cnn_trainer.cpp.s
.PHONY : mnist_cnn_trainer.cpp.s

network_worker_main.o: network_worker_main.cpp.o
.PHONY : network_worker_main.o

# target to build an object file
network_worker_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/network_worker.dir/build.make CMakeFiles/network_worker.dir/network_worker_main.cpp.o
.PHONY : network_worker_main.cpp.o

network_worker_main.i: network_worker_main.cpp.i
.PHONY : network_worker_main.i

# target to preprocess a source file
network_worker_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/network_worker.dir/build.make CMakeFiles/network_worker.dir/network_worker_main.cpp.i
.PHONY : network_worker_main.cpp.i

network_worker_main.s: network_worker_main.cpp.s
.PHONY : network_worker_main.s

# target to generate assembly for a file
network_worker_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/network_worker.dir/build.make CMakeFiles/network_worker.dir/network_worker_main.cpp.s
.PHONY : network_worker_main.cpp.s

pipeline_test.o: pipeline_test.cpp.o
.PHONY : pipeline_test.o

# target to build an object file
pipeline_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipeline_test.dir/build.make CMakeFiles/pipeline_test.dir/pipeline_test.cpp.o
.PHONY : pipeline_test.cpp.o

pipeline_test.i: pipeline_test.cpp.i
.PHONY : pipeline_test.i

# target to preprocess a source file
pipeline_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipeline_test.dir/build.make CMakeFiles/pipeline_test.dir/pipeline_test.cpp.i
.PHONY : pipeline_test.cpp.i

pipeline_test.s: pipeline_test.cpp.s
.PHONY : pipeline_test.s

# target to generate assembly for a file
pipeline_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipeline_test.dir/build.make CMakeFiles/pipeline_test.dir/pipeline_test.cpp.s
.PHONY : pipeline_test.cpp.s

uji_ips_trainer.o: uji_ips_trainer.cpp.o
.PHONY : uji_ips_trainer.o

# target to build an object file
uji_ips_trainer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uji_ips_trainer.dir/build.make CMakeFiles/uji_ips_trainer.dir/uji_ips_trainer.cpp.o
.PHONY : uji_ips_trainer.cpp.o

uji_ips_trainer.i: uji_ips_trainer.cpp.i
.PHONY : uji_ips_trainer.i

# target to preprocess a source file
uji_ips_trainer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uji_ips_trainer.dir/build.make CMakeFiles/uji_ips_trainer.dir/uji_ips_trainer.cpp.i
.PHONY : uji_ips_trainer.cpp.i

uji_ips_trainer.s: uji_ips_trainer.cpp.s
.PHONY : uji_ips_trainer.s

# target to generate assembly for a file
uji_ips_trainer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uji_ips_trainer.dir/build.make CMakeFiles/uji_ips_trainer.dir/uji_ips_trainer.cpp.s
.PHONY : uji_ips_trainer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... run_tests"
	@echo "... tests"
	@echo "... cifar100_cnn_trainer"
	@echo "... cifar10_cnn_trainer"
	@echo "... distributed_pipeline_docker"
	@echo "... mnist_cnn_test"
	@echo "... mnist_cnn_trainer"
	@echo "... network_worker"
	@echo "... pipeline_test"
	@echo "... uji_ips_trainer"
	@echo "... cifar100_cnn_trainer.o"
	@echo "... cifar100_cnn_trainer.i"
	@echo "... cifar100_cnn_trainer.s"
	@echo "... cifar10_cnn_trainer.o"
	@echo "... cifar10_cnn_trainer.i"
	@echo "... cifar10_cnn_trainer.s"
	@echo "... distributed_pipeline_docker.o"
	@echo "... distributed_pipeline_docker.i"
	@echo "... distributed_pipeline_docker.s"
	@echo "... mnist_cnn_test.o"
	@echo "... mnist_cnn_test.i"
	@echo "... mnist_cnn_test.s"
	@echo "... mnist_cnn_trainer.o"
	@echo "... mnist_cnn_trainer.i"
	@echo "... mnist_cnn_trainer.s"
	@echo "... network_worker_main.o"
	@echo "... network_worker_main.i"
	@echo "... network_worker_main.s"
	@echo "... pipeline_test.o"
	@echo "... pipeline_test.i"
	@echo "... pipeline_test.s"
	@echo "... uji_ips_trainer.o"
	@echo "... uji_ips_trainer.i"
	@echo "... uji_ips_trainer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

