function(link_mkl target_name)
    if(ENABLE_MKL)
      if(TARGET MKL::MKL)
          target_link_libraries(${target_name} PRIVATE MKL::MKL)
      else()
          target_include_directories(${target_name} PRIVATE ${MKL_INCLUDE_DIRS})
          target_link_libraries(${target_name} PRIVATE ${MKL_LIBRARIES})
          if(NOT MSVC)
              target_link_libraries(${target_name} PRIVATE pthread m dl)
          endif()
      endif()
    endif()
endfunction()
